---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maestrias-minio-secrets
  namespace: maestrias
spec:
  encryptedData:
    MINIO_ROOT_PASSWORD: AgAT5MhmYz2hMfQaB32p1NmMkVil2CK+z9gbfwtmiiB5ddaNsN4Pesor7kGOADyH7kFAgs3U7dOBDDaQX41mWeXU5t31XO+AWsBj2gnRi9/TakUam9Mh8KqhlR30V0UCvWlR3w+BDJ1fZCnsQ2fTZSZvJG2FB3TTl2i3deUwadIjbBLvDYe57I6yhU5PA6ZBmLqUAhk74/OFGgokim/PZopywZAUFEhSMFaYO6Q3xFBvpjKasOaq7yBbphZV3jQbMUCMVPjlclqWaA1cGpezbF8cafYmwxDfV96Jpwye+9CI6vOHmKkxvHcmK8nRZLJWN0jIQIFNX9onv/yLWEtg9Jf70PR9t8fV6D78WBxOFNM3pDv4qvklQJkVeRUFAOSTyKp272pMwCEk0CwAWA/ij4090LZq5O8MfZ9SyO1h++BdpDPA2nF535mAnEodyd7qy/9M7E4C4jGjdYYZ/Y0S+xX7f5XrDrdJGV5tMFdFY+l8mp66gGgKIuKseRbpaZx9pORNkXCa8ebxKz5FS9nM8EBFp3r8piwoy5fLqC0vbInomXE64mmvO0LZbOdA9J6W6Oz+vObDQQNaFVJqQW1BYpsEX+10diVcLCQjywqPH1LP1b3PURQSZhgcm6AQ7LT2z1jGzYNnjnSdxmNb4Cplmrpu82oBDiCWwgXvVFfryq6MlbLU57rKrNcYzH9ZVawnSwGg902fFb24Ze/U
    MINIO_ROOT_USER: AgBAJ20EUPdqbfS27Tte4Jdh6/GLAw0l6VU2YPrs3ZGuwvFjSbUPk9oJPKB+XNrQc+0IvtmCcQHmdtZHn/1eqCsLIZXCKl5YKQ+lfg3x5D950OtP8mxhF/TtX/TZ4X7h/N0+6/obMGhWE8uO1M/4FvkXOA8kRI5Vjqg6gLfuW/u3KbmYZJM8Dw2knVpw9tfoWiwF2HD7al58s/kQY8HHcEO6FBNx3U8Kaq3W8mJxOic/itYXTIZ6zUhhLu58MleCLjH+NG+EFtjcg0sQG+igcW2CbN8Q/FW6JKQXrBc7mJCXiqhZjjpcNRykjr6MNXIBwiEMXGDwlo0QMGVm7qV6gEGdVnVs7u+tcb/r1QYeOgHFw046H/IiSmcB0auup7o+jTVycOGv1mUTGDCPNOSLU4NarZLh1oyENm8XsToHRP5nY5nX5NvFr7ANguSpFi6HSpEi/aroDRGqQtjo0Jkxj2PloevChvg0k1T7GPmNgOxFflTx0iely0Niont0cyfGmkIyRdWwq90ng7r4PHpLycmcUSHjfNaovaC2hDtPNwLwWJ10jqpzecwbocfMc8WvwgTJGAMcppUq9KTUuCFcHXPH0SXIn7DBLNuof6u9pt3ZIasME48ASeOtR92VDwTpE09Hed6LJXSkDC0oIS6sKzdLU3drHPeRh0cogptI0l6C85E4/iLeM3ctdSSzgm/ZP0kLv2WljOd5VSrN
  template:
    metadata:
      name: maestrias-minio-secrets
      namespace: maestrias
