---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: maestrias
spec:
  encryptedData:
    .dockerconfigjson: AgCjpl3ENFbo3L2nCD3U9thqBfuMF/vbGUR2va13P8ZxNnmcS2xa+pLUI3vX5+Bsk7EaO9h7axEhwRIzAe8WQoKVRj0qkl6nGSFrlafeq9Ka5smYQFCLRyHAcoz9nYtq8d4nzCvtAf6Hyga/SBusB4GEHPFVF9ASJ/PyakWLXA62fWUcgzYmKVrfWeVbOJXweYNcPGSmVHfpROvczm1+a/hoHKNZHQxtwBAKSzKWLuqYe3WrusH4ReZV7RYp0tSev246JY21Xuohsr8GqZkakLcKQE5/s09eGubjK4SUeroVKRkpNlRpNejgwqv5hyCcMifUz1LAu4F0nQ/qakx7yO4zbJeC2kjQSC2lIhJ3VIbeOc7QaxFORLMcGVbDKE+Yxbfdpqq3tAL7MXLIZApmzmnPbP6QR2DI8x09zdWx7+q7TkydLjAJoeReFn6w/wEM6l15PgeGrbmHIsSaJgHNG6DB7bUnmf59sMrWr8Xv4AHt96jCDIaYkQeaqTyrMz1qbDcDfFg/DFbXD8/YP5aK2La+NPz9Y8WKYB1cNrn6Xzc8BUMCbQsDZsEH6Y3arWM02U/QcFGp3AyaUs1RdYWQ6V26siTQ1eXv5uw78T8r1zyVKcf45m089h7lbk4T6FzvWwidCbvOG5NkjAJJrRpQla0KPugeSWXwEJow42HwNCusocdTbpzl9m+F5B5CZ/a8yMtAgiJp7A2B1V2jk3UInCEXVoBQmbrhqvXjwUvJ1HXwXpzaLZBj+f+c8sGH362wcbJLQO90yrxUeB+xa9j/naLqJ6s40R81n9b++ITeE+/fChjMGLvabNPZLGJkpwE6nttNEeSRQd6JTDGygTHwmHPltl1l8tE5PfM5JnSTsliTc5xBmPYnrASSwcWw1HrwDmQTR/v0zY4ZNPB0rf8WumMVvZ6JUEX4BzmkRTDSWwLhhqzC
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: maestrias
    type: kubernetes.io/dockerconfigjson
