---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: maestrias-rabbitmq-secrets
  namespace: maestrias
spec:
  encryptedData:
    RABBITMQ_DEFAULT_PASS: AgCItIamcq7sVEfkEXgLjQy3XVmQXyafu1Po7kdeRqd6zEvAw+unrlIdghvxhnpXw9ASzRNQYuIRmW6j0beVN61U8HeA4J5oQeGeJYfPOU3YQ53dzFhTnK7CCoB+sLv1VmD0pua9s3JGPFaRBCt08ZqSbwMQcM4xlnWdjoYC275M0kwsKmMlu/cb9pADmf/6wfot2Uc2pnEu4dfB4fwHMsvAECbhUReoSRUzAMiGuqcOD3ZO2fOgsmxpBSpH2W+cvVgLjGtKaVJnx0u2cUltsxsj7HP2OB1rgbaUjRGb50jhhdFwFpYRD0//wwc6rRFgoRfT2Xr1FiXXIhMXgfqerjACpiNTlZTgJF/lJNpUSg/+uvOtSXlYtDIqWcEN0RNQynKctUEUVJunmSTZSi17eRvTNunPXriMHnXhfRGIN8E60hG0xDpULl2pNmExMM//RNguUg33VPjirYKZxElRwxQJ/kEIBEySL/zSP4oyAcBEEVzhVpUW1z0ZtOlgwb8VgYApNgugxvf9admZAlYnE8sKhjw2dJ5oKj60NZjGx/K2sUGEg9F5lTDlQYiDL9t8PsLap668+SiZ864ZgdAJifGbeGlumz/UWZXYmzIP/T2Xq0x0QvND9sggQZkwNlHMgBbZoa0fbWoQLEFFEiGxVq8YUoGW6OCSbg4BxrV3mXPDxdguBq5pB4EUMqhNql3XQlgAqimGeQ==
    RABBITMQ_DEFAULT_USER: AgBSNe/kVGpsXR6ShlVADGm7SALalXZ7X9+dJNCxyDLBNjlbj1GujNcAqegNApGJBYbTebzrFL8u6sOvHwCq+kv2U3Nia8c1asFO9TvtTOkPu9fdWlFLFRcP1wzz4Vt4w+EUfPGe/PlLGDMt/WIkS3Md+gkHBBWpJezcJxhB86J1bjPoEzFWiIxNtS6IwX0snu6i2xqpuz3xSmj31/g/ZZe3wWMxx40GlqiXk8EREO43kzongQk+QHPeXTe8z15mPVQj7qqdxksuFl5X7TLDm+dYEnCdZHZ6XAyICmqKWhYXoJgXQ/Z2nIeC4kiRofqufOd9Ev+t2q63A6Ozb1yZb9grqG3EfSf/RDcrdNHi9BvD8z6tc4SkcB88P9yDyrTtwMzV4je4r3KXIgz5yaU93mMpT0c8u0ABHfSsHpiSQOvyKQW5Nj8v+fg4MHI3WKHpzFU+h1uOy++jpdbotqyZmthh7BjwFgmsX4lVr8L7LJrYgfkhE8YP3EtABNHQ/pwhwDceaRBOZJbYFKyKktQDCcjQs6bFjLytFVM8lcFb7SUklaFR+1tUgYJ3EqE2IzoE/3NfSwnss9Fv5V1Hu4Sa3rCoMfqLny9fjR5lOd9vZY5ixQfkOVisQh8RN9Go5gneylK+ncolZMiHH/VrHbhMi2wOJms5rDQ4GemL2X5gsMW7Ulz9jA5U9AjcSEHnR/6XZTZXFW5lGA==
  template:
    metadata:
      name: maestrias-rabbitmq-secrets
      namespace: maestrias
