apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-replica-data
  namespace: galfields
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # igual que db-primary-data (mismo dataset, streaming replication)
