---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: galfields-replication-secret
  namespace: galfields
spec:
  encryptedData:
    REPLICATOR_PASSWORD: AgBgn/pJDYgkPG0shJeOTcmtns4qf/c7MynfyA5q/j0c2Kfm5t+TM9UEk8vUcxYBIOo4X7ZbIrSiSqCNdqeOpAO1yqP8wdvPdAtIdiuQz7af0kxFYOUMhFjoGN6xKruxuNmMQm+qr1n29SndPcekjsFz5UutBbmkq5uBKKIZpjgslvY7VZ9BU7Gu55j0grcJ98sn7VOBNDo1ADh8GqQeTOM1ndTVZPwRFRBWaUYVI06VCZZ3eCqq5qzIstfa3zG7Rt84SXfoYURoGSTeJnr7E9dbPPZwbo2Wvuk6zI2QPUl6GQrae0qgD5HFb+viD6EaaKiHAHZFV1F5BRzKAkpoXP923xtBEG0ub27EZE1wIDZNxA7J2NwI51h3xatQU7rPtkJyVSIEPe9rDSEVBpxl6ZpBtRaFNR/rpZdnP+k7k2min7LD9PCDs0s83d/mKRyYasBq04+Cg0WxhboSSr81lvWDg3ohoSo/ZPIRdsV67xVHqXe8GfcdmJv1vd5iMe+ubAZngqMoGf4afeHteJSRZSYvtGRt2owfoDOQO2UuNmKw/OVOXHkHa+zZo9W3WjEGDnfsg/ioN2DmUaTbL2uWnU/laCGhsg3vJOfPQp8Km8VCnRGMegwwEiZN5e8iUXnxgbUDvvMwazx+wwdsmVuGuKV+ZyymJ2u5wZB5YNvP4/9hyoBePZmP3fF9BaF0TTc+Go7PA2rK7U3gtgXxaiH+CkRIfmbp52h0blsp+CMNXYMjaQ==
  template:
    metadata:
      name: galfields-replication-secret
      namespace: galfields
