---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: galfields
spec:
  encryptedData:
    .dockerconfigjson: AgAz91rjH+aIkB4C4p57DbYbXrJpm6rDIqJOs77mwYnqYuitxuoxI81xmFdQRu7SttHhlZUgWRwFu6whK3hGnPQRcLs4PE0wD/HTDYG2OfxzpOeIcVifii537ov35bp4NCGibb1dcJjlC4OXZURX2w8iO03UyEV5dipE0/kjFmXP8eJ6EN3q8zR7ZTcKiYRwJAPuYv8qcyqG0a2t3QwWyeQyT+vqssIrX66Vh2gW2cj1iMUkva6DOmcWr+AyV95wqsso5jETll6lLbNrqjWtgdkbXBB1smi8gfigge1zZ0i90b+LuhEqa/at4YcGoMNCQEioyO4Hz6OHsYS824nML2+abt+m0tebLr4Iscc8RsHYtmUK5pzmQcgJpCCyOFKYk0N7qVn5HW49yy0jYio9FuLYu4qIEy46CUdPdXfRQKLODDx6q5cCsRYfPiN5Gv6qs60ywlajvTbTx8UwN0O3vkh1OALplFDpRAu7tPhEkOyEdAJL3w/OeFDAiLb5ZtivH5uNidBzrUvGQq82+kiVAo/hjAhJOiAIYe872Z//OqG/aLHBSB4/DZaWYAjjdLV/2B8+0iGiFlR1ke/D2WzxAuNyyFr9wZ0EMtNing9BNz3ASaVGfoKu+L9wPadahTN2rgJxlMTVnY46KTOCnamAGOz8egmh1jeaZ3vgvHrw1x/Rk/RRhf3LFhoFbLiW7TsjfjPfZXPCVwuPhtI4L9XICEBbcz2AcqOcCD3TjcBogyz5DAO9IXkIe2JvkGcZmI0v+YZjEhsbwtzaXzk+P+SpMXECNVjQw+JyrOTEfy5JIhLJHLFlkueL76BHG4ML8hBn7CfRBRaih/dSO1LjhPFyGmNca/aBtm+e4jLD+j2/LSZti/XC25UV362uRtg61R5M1EvrqjUEkUHeNjSBNCP9l9+gqd7pTVV8lX2gG40ZzsZ559Jw
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: galfields
    type: kubernetes.io/dockerconfigjson
