apiVersion: v1
kind: ResourceQuota
metadata:
  name: galfields-quota
  namespace: galfields
spec:
  hard:
    requests.cpu: "1"
    requests.memory: 2Gi
    limits.cpu: "2"
    limits.memory: 3Gi
---
apiVersion: v1
kind: LimitRange
metadata:
  name: galfields-limits
  namespace: galfields
spec:
  limits:
    - type: Container
      defaultRequest:
        cpu: 100m
        memory: 128Mi
      default:
        cpu: 250m
        memory: 256Mi
