---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: galfiends
spec:
  encryptedData:
    .dockerconfigjson: AgByZeB0X/9SNz7ST2ElzaBmm6j+fE1g+AfZ9x9WcPQBdhckYP/oOZU7kWDjJ0hqWNuyebdD8Ne4IiweiXOMYj7v39Vs8RT5SuJObB8Frv1xDRY51EbABj3AntpVFSQfssGdmUkLak92Uql7+duW+iBVCqZiiuhEFo8jWugrfQYF/MumnRy1xK1ZPqFx4KlJehHbredom78h1GvlPOu8hsrJmnnitkRyLaeeBDi0P16sC6598kjA79n8ZdF9XpvJC2GLly8I0sJUSS9hXlgrnimzyfxfeqPdaD1ljTvRcTWtWAwxcUoT4OV8KmQpjRRK8XEaBcLyZR3TWWNcHx/qPstsmaZhNxW3N3XHRYA0nQeg8A/CY8E5hWvI79X+HN4nhZC/9dCNOX936F1i9p0+8Dvym9Po7fn4m20IpJXUzDtvHjB+6nO7QmX3V7X4P/8A3sGeLhTAsuqgDsr+6iDlWvKfYZpOpuW87gQQCay2bgU3SLAdjL7yQpsCNMsXk89tY2rM9F2I4MVOKMRyT4nXqCuqlgMWVHzXUzTcEtVRkAOFbwU5LbXwIQ4Pkh1R1GQt9+h1iCSbKt3DhF/WGbhZ8+4i0ZQi4ZuhXI2Z7FqmkTeZHHwYBtBsOTJvPpo8Ee6WLunU3PkB1Rp7gCatyuKsw5CYoaZbYqP6eiU5nQKNvk67SAQeiUELEtCO+cvPRx4hx3HMWRLAFEBktm74U6okvZUysEc84lCAEQpsKPK91Dvlh4+OaWReOAACe4cAGvwuAexi9klz9V+xJ418ZqyWSbaTNVONDsPcv7jgBk3P+qSaFQweDA1wH3Vyu98Ju0cgOzesi+zGnT/jyadGnxdIpIL5KeJkUAGBF/rPk2cGUcTvGw9z+SXsS91/3yjhJHE+xJK/3duhtDo4zoVBnnDafA9hY+cY83/lF70taU1U1PkDYE9J
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: galfiends
    type: kubernetes.io/dockerconfigjson
